Importing Libraries

In [646]:
# open-ai gym
import gymnasium
import numpy as np
import random as random
import time

In [647]:
environment = gymnasium.make("FrozenLake-v1", is_slippery=False,render_mode='ansi')
observationhaki = environment.reset()
print(environment.render())


SFFF
FHFH
FFFH
HFFG



In [648]:
nb_states = environment.observation_space.n
nb_actions = environment.action_space.n
qtable = np.zeros((nb_states, nb_actions))

# Let's see how q-table has been formed
print('Q-table =')
print(qtable)

Q-table =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [649]:
# random step
action_space = ['Left','Down','Right','Up']
step = random.choice([0,1,2,3])
# or we can use the gymnasium's api for action step
action = environment.action_space.sample()

# move my agent
environment.step(action)
print(environment.render())

  (Left)
SFFF
FHFH
FFFH
HFFG



In [650]:
new_state, reward, terminated, truncated, info = environment.step(2)
print(environment.render())

  (Right)
SFFF
FHFH
FFFH
HFFG



In [651]:
state = environment.reset()
state

(0, {'prob': 1})

In [652]:
episodes = 1000
learning_rate = 0.5 # For learning more on new values rather than old ones
discount = 0.6 # To focus on more future reward since there is only one reward at the end
sequence = []

for _ in range(episodes):
    state, _ = environment.reset()
    done = False

    while not done:
        
        if np.argmax(qtable[state]) > 0:
            action = np.argmax(qtable[state])
        else:
            action = environment.action_space.sample()
        
        sequence.append(action)

        new_state, reward, done,truncated, info = environment.step(action=action)

        # Formula for updating q-table
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + discount * np.max(qtable[new_state]) - qtable[state, action])

        state = new_state


The agent can complete the game without touching any obstacles 

In [653]:
print(environment.render())

  (Right)
SFFF
FHFH
FFFH
HFFG



In [654]:
print(action_space)

['Left', 'Down', 'Right', 'Up']
