Importing Libraries

In [128]:
# open-ai gym
import gymnasium
import numpy as np
import random as random

In [129]:
environment = gymnasium.make("FrozenLake-v1", is_slippery=False,render_mode='ansi')
observationhaki = environment.reset()
print(environment.render())


SFFF
FHFH
FFFH
HFFG



In [130]:
nb_states = environment.observation_space.n
nb_actions = environment.action_space.n
qtable = np.zeros((nb_states, nb_actions))

# Let's see how q-table has been formed
print('Q-table =')
print(qtable)

Q-table =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [131]:
step = random.choice([0,1,2,3,4])

In [132]:
environment.step(step)

(0, 0.0, False, False, {'prob': 1.0})