Importing Libraries

In [5]:
# open-ai gym
import gymnasium
import numpy as np
import random as random

In [6]:
environment = gymnasium.make("FrozenLake-v1", is_slippery=False,render_mode='ansi')
observationhaki = environment.reset()
print(environment.render())


SFFF
FHFH
FFFH
HFFG



In [7]:
nb_states = environment.observation_space.n
nb_actions = environment.action_space.n
qtable = np.zeros((nb_states, nb_actions))

# Let's see how q-table has been formed
print('Q-table =')
print(qtable)

Q-table =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# random step
action_space = ['Left','Down','Right','Up']
step = random.choice([0,1,2,3])
# or we can use the gymnasium's api for action step
action = environment.action_space.sample()

# move my agent
environment.step(action)
print(environment.render())

  (Left)
SFFF
FHFH
FFFH
HFFG



In [9]:
new_state, reward, terminated, truncated, info = environment.step(2)
print(environment.render())

  (Right)
SFFF
FHFH
FFFH
HFFG



In [13]:
state = environment.reset()
state

(0, {'prob': 1})

In [41]:
episodes = 1
learning_rate = 0.9 # For learning more on new values rather than old ones
discount = 0.1 # To focus on more short term reward

for _ in range(episodes):
    state, _ = environment.reset()
    done = False

    while not done:
        action = environment.action_space.sample()
        new_state, reward, done, truncated, info = environment.step(action=action)  
        # Formula for updating q-table
        # qtable[state, action] = qtable[state, action] + learning_rate * (reward + discount * np.max(qtable[new_state]) - qtable[state, action])
        print('new_iteration')

new_iteration
new_iteration
new_iteration
new_iteration
new_iteration
new_iteration
