Importing Libraries

In [253]:
# open-ai gym
import gymnasium
import numpy as np
import random as random

In [254]:
environment = gymnasium.make("FrozenLake-v1", is_slippery=False,render_mode='ansi')
observationhaki = environment.reset()
print(environment.render())


SFFF
FHFH
FFFH
HFFG



In [255]:
nb_states = environment.observation_space.n
nb_actions = environment.action_space.n
qtable = np.zeros((nb_states, nb_actions))

# Let's see how q-table has been formed
print('Q-table =')
print(qtable)

Q-table =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [256]:
# random step
step = random.choice([0,1,2,3])
# or we can use the gymnasium's api for action step
action = environment.action_space.sample()

# move my agent
environment.step(action)
print(environment.render())

  (Up)
SFFF
FHFH
FFFH
HFFG



In [273]:
new_state, reward, terminated, truncated, info = environment.step(2)
print(environment.render())

  (Right)
SFFF
FHFH
FFFH
HFFG



In [275]:
info

{'prob': 1.0}